name: Build Libra Worker Image and Save as Tar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure pnpm is available (corepack + fallback)
        run: |
          set -e
          corepack enable || echo "corepack enable failed"
          corepack prepare pnpm@latest --activate || echo "corepack prepare failed"
          if ! command -v pnpm >/dev/null 2>&1; then
            npm install -g pnpm@latest
          fi
          echo "pnpm version:" && pnpm -v

      - name: Install dependencies (lockfile)
        run: |
          pnpm install --frozen-lockfile --prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image myorg/libra:${IMAGE_TAG}"
          DOCKER_BUILDKIT=1 docker build -t myorg/libra:${IMAGE_TAG} .

      - name: Save Docker image as TAR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mkdir -p output
          TAR_PATH="output/libra-${IMAGE_TAG}.tar"
          docker save myorg/libra:${IMAGE_TAG} -o "$TAR_PATH"
          ls -lh "$TAR_PATH"

      - name: Upload TAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: libra-tar
          path: output/
